server:
  port: 8762

spring:
  application:
    name: zuul-server
    
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
 
zuul:
  routes:
    dataManagement:
      path: /api/**
      serviceId: DATA-MANAGEMENT
      stripPrefix: false
    respositoryData:
      serviceId: REPOSITORY-DATA
      stripPrefix: false
    